apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ensae-mlops
spec:
  project: default
  source:
    repoURL: https://github.com/WolfPackStatMathieu/application-deployment.git
    targetRevision: dev
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: user-mthomassin
  syncPolicy:
    automated:
      selfHeal: true
